# WMS Implements the OGC WMS standard. The WMS service
# uses the JAVA bindings to the OSSIM core library to
# perform all on-the-fly chipping of raw imagery via a
# WMS GetMap query.

FROM ossimlabs/o2-wms
MAINTAINER RadiantBlue Technologies radiantblue.com
LABEL com.radiantblue.version="0.1"\
      com.radiantblue.description="WMS Implements \
      the OGC WMS standard.  The WMS service uses \
      the JAVA bindings to the OSSIM core library to \
      perform all on-the-fly chipping of raw imagery \
      via a WMS GetMap query."\
      com.radiantblue.source=""\
      com.radiantblue.classification="UNCLASSIFIED"

ARG O2_DEV_HOME
RUN rm -f /usr/share/omar/wms-app/wms-app.jar && \
    ln -s $O2_DEV_HOME/apps/wms-app/build/libs/wms-app-1.0.0.jar /usr/share/omar/wms-app/wms-app.jar
