FROM ossimlabs/omar-config-server
MAINTAINER RadiantBlue Technologies radiantblue.com
LABEL com.radiantblue.version=""
ARG O2_DEV_HOME
RUN ln -s $O2_DEV_HOME/support/omar-config-server/build/libs/omar-config-server-0.0.1-SNAPSHOT.jar /usr/share && \
  ln -s $O2_DEV_HOME/support/omar-config-server/config-repo /usr/share/config-repo
