server:
  contextPath:
  port: 8080

environments:
  production:
    dataSource:
      pooled: true
      jmxExport: true
      driverClassName: org.postgresql.Driver
      username: ${DBUSER}
      password: ${DBPASS}
      dialect: 'org.hibernate.spatial.dialect.postgis.PostgisDialect'
      url: jdbc:postgresql://${DBHOST}${DBPORT}/${DBNAME}

quartz:
  jdbcStore: false
  threadPool:
    threadCount: 4

---
grails:
  serverURL: http://${DOCKER_HOST_IP}/o2-stager
  assets:
    url: http://${DOCKER_HOST_IP}/o2-stager/assets/
