server:
  contextPath:
  port: 8080

environments:
  production:
    dataSource:
      pooled: true
      jmxExport: true
      driverClassName: org.postgresql.Driver
      username: ${DBUSER}
      password: ${DBPASS}
      dialect: 'org.hibernate.spatial.dialect.postgis.PostgisDialect'
      url: jdbc:postgresql://${DBHOST}:${DBPORT}/${DBNAME}

omar:
  avro:
    sourceUriField: "S3_URI_Nitf"
    dateField: "Observation_Date"
    dateFieldFormat: "yyyyMMddHHmmss"
    imageIdField: "Image_Id"
    download:
      directory: "/data/s3"
    destination:
      type: "post"
      post:
        addRasterEndPoint: "http://192.168.2.200/stager-app/dataManager/addRaster"
        addRasterEndPointField: "filename"
