# WMTS implements the OGC WMTS standard. The WMTS web app
# uses the WMS and the WFS web services and assumes these
# services are reachable via a http "GET" call from the
# WMTS service. The WMTS service wraps the WMTS service
# call and 1) converts to a WFS query to get the features
# that cover the WMTS query parameters and 2) calls the
# WMS service to chip and return the pixel values that
# satisfy the WMTS request.

FROM 320588532383.dkr.ecr.us-east-1.amazonaws.com/o2-wmts
MAINTAINER RadiantBlue Technologies radiantblue.com
LABEL com.radiantblue.version="0.1"\
      com.radiantblue.description="WMTS implements the \
      OGC WMTS standard. The WMTS web app uses the WMS \
      and the WFS web services and assumes these services \
      are reachable via a http 'GET' call from the WMTS \
      service. The WMTS service wraps the WMTS service \
      call and 1) converts to a WFS query to get the \
      features that cover the WMTS query parameters and \
      2) calls the WMS service to chip and return the \
      pixel values that satisfy the WMTS request."\
      com.radiantblue.source=""\
      com.radiantblue.classification="UNCLASSIFIED"

ARG O2_DEV_HOME

RUN rm -f /usr/share/omar/wmts-app/wmts-app.jar && \
    ln -s $O2_DEV_HOME/apps/wmts-app/build/libs/wmts-app-1.0.0.jar /usr/share/omar/wmts-app/wmts-app.jar
