server:
  contextPath:
  port: 8080

environments:
  production:
    dataSource:
      pooled: true
      jmxExport: true
      driverClassName: org.postgresql.Driver
      username: ${DBUSER}
      password: ${DBPASS}
      dialect: 'org.hibernate.spatial.dialect.postgis.PostgisDialect'
      url: jdbc:postgresql://${DBHOST}${DBPORT}/${DBNAME}

omar:
  wmts:
    wfsUrl: http://${WFSSERVER}/wfs
    wmsUrl: http://${WMSSERVER}/wms
    oldmarWmsFlag: false
    footprints:
      url: http://${WMSSERVER}/footprints/getFootprints
      layers: "omar:raster_entry"
      styles: "byFileType"

---
grails:
  serverURL: http://192.168.99.100/o2-wmts
  assets:
    url: http://192.168.99.100/o2-wmts/assets/
