# The Superoverlay service creates a KML overlay
# for any image found in the indexed database.
# The service calls the WMS chipping servcie and
# allows one to create KML lod nodes to partition
# the dataset into a hierarchical LOD grid.

FROM 320588532383.dkr.ecr.us-east-1.amazonaws.com/o2-superoverlay
MAINTAINER RadiantBlue Technologies radiantblue.com
LABEL com.radiantblue.version="0.1"\
      com.radiantblue.description="The Superoverlay \
      service creates a KML overlay for any image \
      found in the indexed database. The service calls \
      the WMS chipping servcie and allows one to create \
      KML lod nodes to partition the dataset into a \
      hierarchical LOD grid."\
      com.radiantblue.source=""\
      com.radiantblue.classification="UNCLASSIFIED"

ARG O2_DEV_HOME

RUN rm -f /usr/share/omar/superoverlay-app/superoverlay-app.jar && \
    ln -s $O2_DEV_HOME/apps/superoverlay-app/build/libs/superoverlay-app-1.0.0.jar /usr/share/omar/superoverlay-app/superoverlay-app.jar
