# The Superoverlay service creates a KML overlay
# for any image found in the indexed database.
# The service calls the WMS chipping servcie and
# allows one to create KML lod nodes to partition
# the dataset into a hierarchical LOD grid.
