server:
  contextPath:
  port: 8080

environments:
  production:
    dataSource:
      pooled: true
      jmxExport: true
      driverClassName: org.postgresql.Driver
      username: ${DBUSER}
      password: ${DBPASS}
      dialect: 'org.hibernate.spatial.dialect.postgis.PostgisDialect'
      url: jdbc:postgresql://${DBHOST}${DBPORT}/${DBNAME}

wfs:
  featureTypeNamespaces:
    - prefix: omar
      uri: http://omar.ossim.org

  datastores:
    - namespaceId: omar
      datastoreId: ${DBNAME}
      datastoreParams:
        dbtype: postgis
        host: ${DBHOST}
        port: '5432'
        database: ${DBNAME}
        user: ${DBUSER}
        passwd: ${DBPASS}
        'Expose primary keys': 'true'
        namespace: http://omar.ossim.org
  featureTypes:
    - name: raster_entry
      title: raster_entry
      description: ''
      keywords:
        - omar
        - raster_entry
        - features
      datastoreId: ${DBNAME}

    - name: video_data_set
      title: video_data_set
      description: ''
      keywords:
        - omar
        - video_data_set
        - features
      datastoreId: ${DBNAME}

omar:
  superOverlay:
    wmsUrl: http://${WMSURL}/wms/getMap

---
grails:
  serverURL: http://192.168.99.100/o2-superoverlay
  assets:
    url: http://192.168.99.100/o2-superoverlay/assets/
