# The swipe service takes two image ID's as
# input and allows one to swipe, manual flip,
# or auto flip the images to see changes. It
# uses existing WFS and WMS services. The WFS
# is used to query the holding for the datasets
# used in the swipe. The WMS chips data displayed
# in the swipe view.

FROM 320588532383.dkr.ecr.us-east-1.amazonaws.com/o2-swipe
MAINTAINER RadiantBlue Technologies radiantblue.com
LABEL com.radiantblue.version="0.1"\
      com.radiantblue.description="The swipe \
      service takes two image ID's as input and \
      allows one to swipe, manual flip, the images \
      to see changes. It uses existing WFS and WMS \
      services. The WFS is used to query the holding \
      for the datasets used in the swipe. The WMS \
      chips data displayed in the swipe view."\
      com.radiantblue.source=""\
      com.radiantblue.classification="UNCLASSIFIED"

ARG O2_DEV_HOME

RUN rm -f /usr/share/omar/swipe-app/swipe-app.jar && \
      ln -s $O2_DEV_HOME/apps/swipe-app/build/libs/swipe-app-1.0.0.jar /usr/share/omar/swipe-app/swipe-app.jar
