server:
  contextPath:
  port: 8080

environments:
  production:
    dataSource:
      pooled: true
      jmxExport: true
      driverClassName: org.postgresql.Driver
      username: ${DBUSER}
      password: ${DBPASS}
      dialect: 'org.hibernate.spatial.dialect.postgis.PostgisDialect'
      url: jdbc:postgresql://${DBHOST}${DBPORT}/${DBNAME}

swipe:
  app:
    wfs:
      baseUrl: http://${WFSURL}/wfs?
    wms:
      baseUrl: http://${WMSURL}/wms?

endpoints:
  health:
    enabled: true

---
grails:
  serverURL: http://${DOCKER_HOST_IP}/o2-swipe
  assets:
    url: http://${DOCKER_HOST_IP}/o2-swipe/assets/
