server:
  contextPath:
  port: 8080

environments:
  production:
    dataSource:
      pooled: true
      jmxExport: true
      driverClassName: org.postgresql.Driver
      username: ${DBUSER}
      password: ${DBPASS}
      dialect: 'org.hibernate.spatial.dialect.postgis.PostgisDialect'
      url: jdbc:postgresql://${DBHOST}${DBPORT}/${DBNAME}

swipe:
  app:
    wfs:
      baseUrl: http://${WFSURL}:${WFSPORT}/wfs?
    wms:
      baseUrl: http://${WMSURL}:${WMSPORT}/wms?

---
grails:
  serverURL: http://localhost:8080
  assets:
    url: http://localhost:8080/assets/
