apiVersion: v1
kind: Pod
metadata:
  name: wmtsapp
  labels:
    name: wmtsapp
spec:
  containers:
  - name: wmts-app
    env:
    - name: WMSSERVER
      value: http://otd-omar-single.rbtcloud.dev
    - name: WFSPORT
      value: "80"
    - name: WFSSERVER
      value: http://otd-omar-single.rbtcloud.dev
    - name: WFSPORT
      value: "80"
    - name: DBHOST
      value: "127.0.0.1"
    - name: DBUSER
      value: wmts
    - name: DBPORT
      value: "5432"
    - name: DBNAME
      value: omar_prod
    - name: DBUSER
      value: wmts
    - name: DBPASS
      value: abc123
    image: radiantbluetechnologies/wmts
    ports:
    - containerPort: 8080
      name: wmts

