# The Download Web Service takes multiple
# images or image groups specified in a
# JSON and return a zip archive.
FROM ossimlabs/o2-download
MAINTAINER RadiantBlue Technologies radiantblue.com
LABEL com.radiantblue.version="0.1"\
      com.radiantblue.description="he Download \
      Web Service takes multiple images or image \
      groups specified in a JSON and return a zip \
      archive."\
      com.radiantblue.source=""\
      com.radiantblue.classification="UNCLASSIFIED"

ARG O2_DEV_HOME

RUN rm -f /usr/share/omar/download-app/download-app.jar && \
      ln -s $O2_DEV_HOME/apps/download-app/build/libs/download-app-1.0.0.jar /usr/share/omar/download-app/download-app.jar
