server:
  contextPath: /o2-download
  port: 8080

environments:
  production:
    dataSource:
      pooled: true
      jmxExport: true
      driverClassName: org.postgresql.Driver
      username: ${DBUSER}
      password: ${DBPASS}
      dialect: 'org.hibernate.spatial.dialect.postgis.PostgisDialect'
      url: jdbc:postgresql://${DBHOST}:${DBPORT}/${DBNAME}

endpoints:
  health:
    enabled: true

---
grails:
 serverURL: http://${DOCKER_HOST_IP}/o2-download
#  assets:
#    url: http://${DOCKER_HOST_IP}/o2-download/assets/

spring:
  cloud:
    config:
      enabled: false
    discovery:
      enabled: false
