# WFS Implements the OGC WFS standard. The Web Feature
# Service (WFS) supports returning feature information
# indexed into either the imagery tables or the video tables.

FROM ossimlabs/o2-wfs
MAINTAINER RadiantBlue Technologies radiantblue.com
LABEL com.radiantblue.version="0.1"\
      com.radiantblue.description="WFS Implements \
      the OGC WFS standard.  The Web Feature Service \
      (WFS) supports returning feature information \
      indexed into either the imagery tables or the \
       video tables."\
      com.radiantblue.source=""\
      com.radiantblue.classification="UNCLASSIFIED"

ARG O2_DEV_HOME

RUN rm /usr/share/omar/wfs-app/wfs-app.jar && \
    ln -s $O2_DEV_HOME/apps/wfs-app/build/libs/wfs-app-1.0.0.jar /usr/share/omar/wfs-app/wfs-app.jar

EXPOSE 8080
CMD ["sh", "/usr/share/omar/wfs-app/wfs-app.sh"]
