# Twofishes is not owned or packaged by us
# and the full installation instructions can
# be found at their location. Twofishes
# location service is used by the OMAR/O2 UI

FROM radiantbluetechnologies/o2-base
MAINTAINER RadiantBlue Technologies radiantblue.com
LABEL com.radiantblue.version="0.1"\
      com.radiantblue.description="Twofishes is\
      not owned or packaged by us and the full\
      installation instructions can be found at\
      their location. Twofishes location service\
      is used by the OMAR/O2 UI."\
      com.radiantblue.source=""\
      com.radiantblue.classification="UNCLASSIFIED"

EXPOSE 8080 8081 8082 8083
