avro{
  sourceUriField="S3_URI_Nitf"
  dateField="Observation_Date"
  dateFieldFormat="yyyyMMddHHmmss"
  imageIdField="Image_Id"
  createDirectoryRetry="3"
  createDirectoryRetryWaitInMillis="100"
  download{
    directory="/data"
  }
  destination{
    type="post"
    post{
      addRasterEndPoint="http://192.168.2.200/stager-app/dataManager/addRaster"
      addRasterEndPointField="filename"
      addRasterEndPointParams{
        background="true"
        buildHistograms="true"
        buildOverviews="true"
        overviewCompressionType="NONE"
        overviewType="ossim_tiff_box"
        filename=""
      }
    }
  }
}