# ---------------------------------------
# MapProxy example seeding configuration.
# ---------------------------------------
#
# This is a minimal MapProxy seeding configuration.
# See full_seed_example.yaml and the documentation for more options.
#

seeds:
  myseed1:
    caches: [o2_bright_tiles_cache]
    # grids: []
    # coverages: [austria]
    # levels:
    #   to: 3
    # seed from level 3 to 6 (including level 3 and 6)
    levels: #[9]
      from: 6
      to: 8
    # refresh_before:
    #   time: 2013-10-10T12:35:00

# cleanups:
#   myclean1:
#     caches: [o2_basic_tiles_geo_cache]
#     remove_before:
#       days: 14
#     levels:
#         from: 11

coverages:
  austria:
      bbox: [9.36, 46.33, 17.28, 49.09]
      srs: 'EPSG:4326'
