FROM ossimlabs/omar-eureka-server
MAINTAINER RadiantBlue Technologies radiantblue.com
LABEL com.radiantblue.version=""
ARG O2_DEV_HOME
RUN ln -s $O2_DEV_HOME/support/omar-eureka-server/build/libs/omar-eureka-server-0.0.1-SNAPSHOT.jar /usr/share
