#!/bin/bash
export PROGRAM_PID=$1

pushd `dirname $0` > /dev/null
export SCRIPT_DIR=`pwd -P`
popd >/dev/null

if [ -z ${JAVA_OPTS} ] ; then
   JAVA_OPTS="-server -Xms256m -Xmx1024m -Djava.awt.headless=true -XX:+CMSClassUnloadingEnabled -XX:+UseGCOverheadLimit"
fi

PROGRAM_NAME={{program_name}}
if [ -z $OSSIM_INSTALL_PREFIX ]; then
   export OSSIM_INSTALL_PREFIX={{OSSIM_INSTALL_PREFIX}}
fi

if [ -z $WORKING_DIR ]; then
   pushd $SCRIPT_DIR
else
   pushd $WORKING_DIR
fi


###########
# Need to have the OSSIM_PREFS_FILE defined
##########
if [ -f /etc/profile.d/ossim.sh ] ; then
source /etc/profile.d/ossim.sh
fi


if [ -z $PROGRAM_PID ]; then
java $JAVA_OPTS -jar ${SCRIPT_DIR}/${PROGRAM_NAME}.jar --spring.config.location=${SCRIPT_DIR}/${PROGRAM_NAME}.yml
else
java $JAVA_OPTS -jar ${SCRIPT_DIR}/${PROGRAM_NAME}.jar --spring.config.location=${SCRIPT_DIR}/${PROGRAM_NAME}.yml&
sleep 1
echo $! >$PROGRAM_PID
fi

popd > /dev/null

exit 0
