# eureka:
#   client:
#     serviceUrl:
#       defaultZone: http://localhost:8761/eureka/
# ---
# spring:
#   profiles: production
# eureka:
#   client:
#     serviceUrl:
#       defaultZone: http://omar-eureka-server:8761/eureka/
---
server:
  port: 8765
zuul:
  ignoredServices: "*"
  add-proxy-headers: true
  routes:
    all-app:
      path: /all-app/**
      serviceId: omar-all-app
      strip-prefix: false
    omar-app:
      path: /omar/**
      serviceId: omar-gui-app
      strip-prefix: false
