# eureka:
#   client:
#     serviceUrl:
#       defaultZone: http://localhost:8761/eureka/
# ---
# spring:
#   profiles: production
# eureka:
#   client:
#     serviceUrl:
#       defaultZone: http://omar-eureka-server:8761/eureka/
---
server:
  port: 8765
zuul:
  ignoredServices: "*"
  # add-proxy-headers: true
  routes:
    all-app:
      path: /o2-services/**
      serviceId: o2-services
      //strip-prefix: false
    omar-app:
      path: /o2-omar/**
      serviceId: o2-omar
      //strip-prefix: false
