# eureka:
#   client:
#     serviceUrl:
#       defaultZone: http://localhost:8761/eureka/
# ---
# spring:
#   profiles: production
# eureka:
#   client:
#     serviceUrl:
#       defaultZone: http://omar-eureka-server:8761/eureka/
---
server:
  port: 8765
zuul:
  ignoredServices: "*"
  # add-proxy-headers: true
  routes:
    o2-mensa:
      path: /o2-mensa/**
      serviceId: o2-mensa
      strip-prefix: false
    o2-wfs:
      path: /o2-wfs/**
      serviceId: o2-wfs
      strip-prefix: false
    o2-wms:
      path: /o2-wms/**
      serviceId: o2-wms
      strip-prefix: false
    omar-app:
      path: /o2-omar/**
      serviceId: o2-omar
      strip-prefix: false
