# The OMAR Web application, nicknamed O2, is a
# springboard for the new O2 services and allows
# one to quickly discover new assets and display
# them using common OGC services.

FROM 320588532383.dkr.ecr.us-east-1.amazonaws.com/o2-omar
MAINTAINER RadiantBlue Technologies radiantblue.com
LABEL com.radiantblue.version="0.1"\
      com.radiantblue.description="The OMAR Web \
      application, nicknamed O2, is a springboard \
      for the new O2 services and allows one to \
      quickly discover new assets and display them \
      using common OGC services."\
      com.radiantblue.source=""\
      com.radiantblue.classification="UNCLASSIFIED"

ARG O2_DEV_HOME

RUN rm /usr/share/omar/omar-app/omar-app.jar && \
    ln -s $O2_DEV_HOME/apps/omar-app/build/libs/omar-app-1.0.0.jar /usr/share/omar/omar-app/omar-app.jar
