server:
  contextPath:
  port: 8080

environments:
  production:
    dataSource:
      pooled: true
      jmxExport: true
      driverClassName: org.postgresql.Driver
      username: postgres_user
      password: abc123
      dialect: 'org.hibernate.spatial.dialect.postgis.PostgisDialect'
      url: jdbc:postgresql://${DBHOST}${DBPORT}/omar_prod

omar:
  openlayers:
    baseMaps:
      -
        layerType: "tile"
        title: "Open Street Map"
        url: "http://vmap0.tiles.osgeo.org/wms/vmap0"
        params:
          layers: "basic,coastline_01,coastline_02,priroad,secroad,rail,ferry,tunnel,bridge,trail,CAUSE,clabel,statelabel,ctylabel"
          format: "image/jpeg"
        options:
          visible: true
  app:
    root:
      baseUrl: http://o2-omar/omar-app
    wfs:
      baseUrl: http://${WFSURL}:${WFSPORT}/wfs?
      enabled: true
      proxy: /proxy/index?url=
    wms:
      baseUrl: http://${WMSURL}:${WMSPORT}/wms?
      enabled: true
    imageSpace:
      baseUrl: http://${WMSURL}:${WMSPORT}/imageSpace
      enabled: true
    thumbnails:
      baseUrl: http://${WMSURL}:${WMSPORT}/imageSpace/getThumbnail?
    footprints:
      baseUrl: http://${WMSURL}:${WMSPORT}/footprints/getFootprints
    # kmlApp:
    #   baseUrl: http://192.168.2.200/superoverlay-app
    # predio:
    #   baseUrl: http://192.168.2.200/predio-app/predio/
    #   enabled: false
    # twofishes:
    #   baseUrl: http://<ip>:<port>/twofish
    #   proxy: /twoFishesProxy
    # swipeApp:
    #   baseUrl: http://192.168.2.200/swipe-app/swipe
    #   enabled: true
    # jpipApp:
    #   baseUrl: http://192.168.2.200/jpip-app/jpip
    #   enabled: true
    # piwikApp:
    #   baseUrl: http://<url>/piwik/
    #   enabled: true
    apiApp:
      baseUrl: http://o2-omar/api
      enabled: true
    misc:
      icons:
        green-marker: search_marker_green.png

classificationBanner:
  backgroundColor: green
  classificationType: Unclassified

# ---
# grails:
#   serverURL: http://${UIHOST}:${UIPORT}
#   assets:
#     url: http://${UIHOST}:${UIPORT}/assets/
