server:
  contextPath:
  port: 8080

environments:
  production:
    dataSource:
      pooled: true
      jmxExport: true
      driverClassName: org.postgresql.Driver
      username: postgres_user
      password: abc123
      dialect: 'org.hibernate.spatial.dialect.postgis.PostgisDialect'
      url: jdbc:postgresql://${DBHOST}${DBPORT}/omar_prod

omar:
  openlayers:
    baseMaps:
      -
        layerType: "tile"
        title: "Open Street Map"
        url: "http://vmap0.tiles.osgeo.org/wms/vmap0"
        params:
          layers: "basic,coastline_01,coastline_02,priroad,secroad,rail,ferry,tunnel,bridge,trail,CAUSE,clabel,statelabel,ctylabel"
          format: "image/jpeg"
        options:
          visible: true
  app:
    # root:
    #   baseUrl: http://o2-omar/omar-app
    wfs:
      baseUrl: http://${WFSURL}/wfs?
      enabled: true
      proxy: /proxy/index?url=
    wms:
      baseUrl: http://${WMSURL}/wms?
      enabled: true
    imageSpace:
      baseUrl: http://${WMSURL}/imageSpace
      enabled: true
    thumbnails:
      baseUrl: http://${WMSURL}/imageSpace/getThumbnail
    footprints:
      baseUrl: http://${WMSURL}/footprints/getFootprints
    stagerApp:
      baseUrl: http://${STAGERURL}:${STAGERPORT}
    downloadApp:
      baseUrl: http://${DOWNLOADURL}
    kmlApp:
      baseUrl: http://${KMLURL}/
    predio:
      baseUrl: http://${PREDIOURL}:${PREDIOPORT}/predio/
      enabled: ${PREDIOENABLED}
    twofishes:
      baseUrl: http://${TWOFISHURL}/twofish
      proxy: /twoFishesProxy
    swipeApp:
      baseUrl: http://${SWIPEURL}/swipe
      enabled: ${SWIPEENABLED}
    jpipApp:
      baseUrl: http://${JPIPURL}:${JPIPPORT}/jpip
      enabled: ${JPIPENABLED}
    wmtsApp:
      baseUrl: http://${WMTSURL}/wmtsApp/index
      enabled: ${WMTSENABLED}
    piwikApp:
      baseUrl: http://${PIWIKURL}:${PWIKPORT}/piwik/
      enabled: ${PWIKENABLED}
    apiApp:
      baseUrl: http://${APIURL}:${APIPORT}/api
      enabled: ${APIENABLED}
    misc:
      icons:
        green-marker: search_marker_green.png

classificationBanner:
  backgroundColor: ${BANNERCOLOR}
  classificationType: ${BANNERCLASSIFICATION}

---
grails:
  serverURL: http://192.168.99.100/o2-omar
  assets:
    url: http://192.168.99.100/o2-omar/assets/
