# The mensuration service takes image
# points and the image file associated
# with those image points and do different
# forms of measurements. The service
# supports calculating linear and geodetic
# distances based on a path and if the path
# also defines a polygon it will add in
# support for area calculation. We also
# support transforming the image point to
# ground and, if supported by the sensor,
# add in an optional position quality to
# show the horizontal and vertical error
# based on the underlying surface elevation
# used.

FROM 320588532383.dkr.ecr.us-east-1.amazonaws.com/o2-mensa
MAINTAINER RadiantBlue Technologies radiantblue.com
LABEL com.radiantblue.version="0.1"\
      com.radiantblue.description="The mensuration \
      service takes image points and the image file \
      associated with those image points and do \
      different forms of measurements. The service \
      supports calculating linear and geodetic \
      distances based on a path and if the path \
      also defines a polygon it will add in support \
      for area calculation. We also support transforming \
      the image point to ground and, if supported by the \
      sensor, add in an optional position quality to show \
      the horizontal and vertical error based on the \
      underlying surface elevation used." \
      com.radiantblue.source=""\
      com.radiantblue.classification="UNCLASSIFIED"

ARG O2_DEV_HOME

RUN rm -f /usr/share/omar/mensa-app/mensa-app.jar && \
    ln -s $O2_DEV_HOME/apps/mensa-app/build/libs/mensa-app-1.0.0.jar /usr/share/omar/mensa-app/mensa-app.jar
