baseLayers:
    osmBasic:
        name: OSM Basic
        type: xyz
        url: http://o2.radiantbluecloud.com/o2-basemap/styles/basic-v9/rendered/{z}/{x}/{y}.png
        visible: false
    osmBright:
        name: OSM Bright
        type: xyz
        visible: true
        url: http://o2.radiantbluecloud.com/o2-basemap/styles/bright-v9/rendered/{z}/{x}/{y}.png

baseUrl: http://${BASE_URL}

beLookupUrl: http://${BE_LOOKUP_URL}/wfs

defaultLocation: 48.8584, 2.2945

docsUrl: http://${DOCS_URL}

geocoderUrl: http://${GEOCODER_URL}

libraries:
    o2:
        label: O2
        layerType: wms
        name: o2
        sensors: []
        queryUrl: http://${WFSURL}/wfs
        viewUrl: http://${WMSURL}/wms

networkSpecific:
    dialogs:
        enabled: true
    layers:
        enabled: true

securityClassification: UNCLASSIFIED

server:
  contextPath: /tlv
  port: 8080

---
# grails:
#   serverURL: http://${DOCKER_HOST_IP}/tlv
#   assets:
#     url: http://${DOCKER_HOST_IP}/tlv/assets/

spring:
  cloud:
    config:
      enabled: false
    discovery:
      enabled: false
