apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv01 
spec:
  capacity:
    storage: 500Gi
  accessModes:
  - ReadWriteMany
  nfs:
    path: /data
    server: oc2s-o2-nfs-server.rbtcloud.com
  persistentVolumeReclaimPolicy: Recycle
