version: '2'
services:
  o2-mensa:
    build: ./o2-mensa
    container_name: o2-mensa
    environment:
      DOCKER_HOST_IP: localhost
    image: ${DOCKER_REGISTRY_URI}/o2-mensa
    ports:
      - "5014:8080"
    volumes:
      - /Users:/Users
  o2-omar:
    build: ./o2-omar
    container_name: o2-omar
    environment:
      APIENABLED: "false"
      APIPORT:
      APIURL:
      BANNERCOLOR: green
      BANNERCLASSIFICATION: Unclassified
      DBHOST: o2-db
      DBNAME: omar_prod
      DBPASS: abc123
      DBPORT: 5432
      DBUSER: postgres_user
      DOCKER_HOST_IP: localhost
      DOWNLOADPORT:
      DOWNLOADURL: localhost/o2-download
      JPIPENABLED: "true"
      JPIPPORT:
      JPIPURL:
      KMLPORT:
      KMLURL: localhost/o2-superoverlay
      PREDIOENABLED: "false"
      PREDIOPORT:
      PREDIOURL: localhost/o2-predio
      PWIKENABLED: "true"
      PWIKPORT:
      PWIKURL:
      STAGERPORT:
      STAGERURL: localhost/o2-stager
      TWOFISHPORT:
      TWOFISHURL: localhost/twofishes
      WFSPORT:
      WFSURL: localhost/o2-wfs
      WMSPORT:
      WMSURL: localhost/o2-wms
      WMTSENABLED: "true"
      WMTSPORT:
      WMTSURL: localhost/o2-wmts
    image: ${DOCKER_REGISTRY_URI}/o2-omar
    ports:
      - "5010:8080"
    volumes:
      - /Users:/Users
  o2-wfs:
    build: ./o2-wfs
    container_name: o2-wfs
    environment:
      DBHOST: o2-db
      DBNAME: omar_prod
      DBPASS: abc123
      DBPORT: 5432
      DBUSER: postgres_user
      DOCKER_HOST_IP: localhost
      O2URL: localhost/o2-omar
      TLV_URL: localhost/tlv
      WFSURL: localhost/o2-wfs
      WMSURL: localhost/o2-wms
    image: ${DOCKER_REGISTRY_URI}/o2-wfs
    ports:
      - "4998:8080"
    volumes:
      - /Users:/Users
  o2-wms:
    build: ./o2-wms
    container_name: o2-wms
    environment:
      DBHOST: o2-db
      DBNAME: omar_prod
      DBPASS: abc123
      DBPORT: 5432
      DBUSER: postgres_user
      DOCKER_HOST_IP: localhost
    image: ${DOCKER_REGISTRY_URI}/o2-wms
    ports:
      - "4997:8080"
    volumes:
      - /Users:/Users
