version: '2'
services:
  o2-web-proxy:
    build:
      args:
        - O2_DEV_HOME=${O2_DEV_HOME}
      context: ./o2-web-proxy
      dockerfile: Dockerfile-dev
    environment:
      DOCKER_HOST_IP: 172.16.0.109
    image: ossimlabs/o2-web-proxy-dev
    ports:
      - "80:80"
    restart: always
    volumes:
      - /home:/home
      - /Users:/Users
