# Expected shell environment variables available to docker-compose (examples in parens):
# See docker-common.sh
#
# DOCKER_REGISTRY_URI  (320588532383.dkr.ecr.us-east-1.amazonaws.com)
# DOCKER_HOST_URL      (o2.radiantbluecloud.com)
# AWS_CREDENTIALS_PATH ("/home/jenkins/.aws:/root/.aws")

version: '2'
services:
  o2-avro:
    container_name: o2-avro
    environment:
      ADDRASTERENDPOINTPORT: :8080
      ADDRASTERENDPOINTURL: o2-stager
      DBHOST: o2-db
      DBNAME: omar_prod
      DBPASS: abc123
      DBPORT: 5432
      DBUSER: postgres_user
      DOCKER_HOST_IP: ${DOCKER_HOST_URL}
      OSSIM_DATA: /data
      SPRING_CLOUD_CONFIG_ENABLED: "false"
      SPRING_CLOUD_DISCOVERY_ENABLED: "false"
    image: ${DOCKER_REGISTRY_URI}/o2-avro:${TAG}
    ports:
      - "5001:8080"
    restart: always
    volumes:
      - /data:/data
  o2-basemap:
    container_name: o2-basemap
    image: ${DOCKER_REGISTRY_URI}/o2-basemap
    ports:
      - "5016:80"
    restart: always
    # Location of the .mbtiles file for the base map
    # /basemap on the host to /data in the o2-basemap container
    volumes:
      - /basemap:/data
  o2-mapproxy:
    container_name: o2-mapproxy
    image: ${DOCKER_REGISTRY_URI}/o2-mapproxy
    ports:
      - "5017:8080"
    # Mount a volume/directory "mapproxy" from the
    # container to the host to hold the configuration files
    # and cache for the base maps.
    volumes:
      - /basemap-cache:/mapproxy
  o2-db:
    container_name: o2-db
    environment:
      POSTGRES_DB: omar_prod
      POSTGRES_PASSWORD: abc123
      POSTGRES_USER: postgres_user
    image: ${DOCKER_REGISTRY_URI}/o2-db
    ports:
      - "4990:5432"
    restart: always
  o2-disk-cleanup:
    container_name: o2-disk-cleanup
    environment:
      O2_DISK_VOLUME: /data
      O2_MAX_DISK_LIMIT: 0.9
      O2_MIN_DISK_LIMIT: 0.8
      JDBC_CONNECTION_STRING: jdbc:postgresql://o2-db:5432/omar_prod
      POSTGRES_PASSWORD: abc123
      POSTGRES_USER: postgres_user
      STAGER_URL: ${DOCKER_HOST_URL}/o2-stager
    image: ${DOCKER_REGISTRY_URI}/o2-disk-cleanup:${TAG}
    ports:
      - "4991:8080"
    volumes:
      - /data:/data
    restart: always
  o2-download:
    container_name: o2-download
    environment:
      DBHOST: o2-db
      DBNAME: omar_prod
      DBPASS: abc123
      DBPORT: 5432
      DBUSER: postgres_user
      DOCKER_HOST_IP: ${DOCKER_HOST_URL}
      OSSIM_DATA: /data
      SPRING_CLOUD_CONFIG_ENABLED: "false"
      SPRING_CLOUD_DISCOVERY_ENABLED: "false"
    image: ${DOCKER_REGISTRY_URI}/o2-download:${TAG}
    ports:
      - "5011:8080"
    restart: always
    volumes:
      - /data:/data
  o2-jpip:
    container_name: o2-jpip
    environment:
      DBHOST: o2-db
      DBNAME: omar_prod
      DBPASS: abc123
      DBPORT: 5432
      DBUSER: postgres_user
      DOCKER_HOST_IP: ${DOCKER_HOST_URL}
      JPIPCACHEDIR: /data/jpip-cache
      JPIPSERVERPORT: 5004
      JPIPSERVERURL: ${DOCKER_HOST_URL}
      OSSIM_DATA: /data
      SPRING_CLOUD_CONFIG_ENABLED: "false"
      SPRING_CLOUD_DISCOVERY_ENABLED: "false"
    image: ${DOCKER_REGISTRY_URI}/o2-jpip:${TAG}
    ports:
      - "5003:8080"
    restart: always
    volumes:
      - /data:/data
  o2-jpip-server:
    container_name: o2-jpip-server
    environment:
      DOCKER_HOST_IP: ${DOCKER_HOST_URL}
      JPIPCACHEDIR: /data/jpip-cache
      JPIPSERVERPORT: 8080
      JPIPSERVERURL: localhost
      SPRING_CLOUD_CONFIG_ENABLED: "false"
      SPRING_CLOUD_DISCOVERY_ENABLED: "false"
    image: ${DOCKER_REGISTRY_URI}/o2-jpip-server:${TAG}
    ports:
      - "5004:8080"
    restart: always
    volumes:
      - /data:/data
  o2-mensa:
    container_name: o2-mensa
    environment:
      DOCKER_HOST_IP: ${DOCKER_HOST_URL}
      OSSIM_DATA: /data
      SPRING_CLOUD_CONFIG_ENABLED: "false"
      SPRING_CLOUD_DISCOVERY_ENABLED: "false"
    image: ${DOCKER_REGISTRY_URI}/o2-mensa:${TAG}
    ports:
      - "5014:8080"
    volumes:
      - /data:/data
  o2-twofishes:
    container_name: twofishes
    image: ${DOCKER_REGISTRY_URI}/twofishes
    ports:
      - "5006:8081"
    restart: always
  o2-omar:
    container_name: o2-omar
    environment:
      APIENABLED: "false"
      APIPORT:
      APIURL:
      BANNERCOLOR: green
      BANNERCLASSIFICATION: Unclassified
      DBHOST: o2-db
      DBNAME: omar_prod
      DBPASS: abc123
      DBPORT: 5432
      DBUSER: postgres_user
      DOCKER_HOST_IP: ${DOCKER_HOST_URL}
      DOWNLOADPORT:
      DOWNLOADURL: ${DOCKER_HOST_URL}/o2-download
      JPIPENABLED: "true"
      JPIPPORT:
      JPIPURL: ${DOCKER_HOST_URL}/o2-jpip
      KMLPORT:
      KMLURL: ${DOCKER_HOST_URL}/o2-superoverlay
      MENSAPORT:
      MENSAURL: ${DOCKER_HOST_URL}/o2-mensa
      PREDIOENABLED: "false"
      PREDIOPORT:
      PREDIOURL: ${DOCKER_HOST_URL}/o2-predio
      PWIKENABLED: "false"
      PWIKPORT:
      PWIKURL:
      SPRING_CLOUD_CONFIG_ENABLED: "false"
      SPRING_CLOUD_DISCOVERY_ENABLED: "false"
      STAGERPORT:
      STAGERURL: ${DOCKER_HOST_URL}/o2-stager
      TLVAPPENABLED: "true"
      TLVENABLED: "true"
      TLVPORT:
      TLVAPPURL: ${DOCKER_HOST_URL}
      TLVURL: ${DOCKER_HOST_URL}/tlv
      TWOFISHPORT:
      TWOFISHURL: ${DOCKER_HOST_URL}/twofishes
      USER_GUIDE_ENABLED: "true"
      USER_GUIDE_URL: ossimlabs.s3-website-us-east-1.amazonaws.com/o2/docs/
      WFSPORT:
      WFSURL: ${DOCKER_HOST_URL}/o2-wfs
      WMSPORT:
      WMSURL: ${DOCKER_HOST_URL}/o2-wms
      WMTSENABLED: "true"
      WMTSPORT:
      WMTSURL: ${DOCKER_HOST_URL}/o2-wmts
    image: ${DOCKER_REGISTRY_URI}/o2-omar:${TAG}
    ports:
      - "5010:8080"
    restart: always
  o2-sqs:
    container_name: o2-sqs
    environment:
      AWSDNS: ${AWSDNS}
      AWSQUEUEPATH: ${AWSQUEUEPATH}
      DESTINATION_POST_END_POINT: o2-avro
      DESTINATION_POST_END_POINT_PORT: :8080
      DESTINATION_POST_FIELD: message
      DESTINATION_TYPE: post
      DOCKER_HOST_IP: ${DOCKER_HOST_URL}
      NUMBER_OF_MESSAGES: 1
      POLgG_INTERVAL_SECONDS: 10
      SPRING_CLOUD_CONFIG_ENABLED: "false"
      SPRING_CLOUD_DISCOVERY_ENABLED: "false"
      WAIT_TIME_SECONDS: 20
    image: ${DOCKER_REGISTRY_URI}/o2-sqs:${TAG}
    ports:
      - "5000:8080"
    restart: always
#    volumes:
      # Modify the path below to reflect your
      # AWS credentials location.
#      - ${AWS_CREDENTIALS_PATH}
  o2-stager:
    container_name: o2-stager
    environment:
      DBHOST: o2-db
      DBNAME: omar_prod
      DBPASS: abc123
      DBPORT: 5432
      DBUSER: postgres_user
      DOCKER_HOST_IP: ${DOCKER_HOST_URL}
      OSSIM_DATA: /data
      SPRING_CLOUD_CONFIG_ENABLED: "false"
      SPRING_CLOUD_DISCOVERY_ENABLED: "false"
    image: ${DOCKER_REGISTRY_URI}/o2-stager:${TAG}
    ports:
      - "5002:8080"
    restart: always
    volumes:
      - /data:/data
  o2-superoverlay:
    container_name: o2-superoverlay
    environment:
      DBHOST: o2-db
      DBNAME: omar_prod
      DBPASS: abc123
      DBPORT: 5432
      DBUSER: postgres_user
      DOCKER_HOST_IP: ${DOCKER_HOST_URL}
      O2URL: ${DOCKER_HOST_URL}/o2-omar
      OSSIM_DATA: /data
      SPRING_CLOUD_CONFIG_ENABLED: "false"
      SPRING_CLOUD_DISCOVERY_ENABLED: "false"
      TLV_URL: ${DOCKER_HOST_URL}/tlv
      WFSURL: ${DOCKER_HOST_URL}/o2-wfs
      WMSPORT:
      WMSURL: ${DOCKER_HOST_URL}/o2-wms
    image: ${DOCKER_REGISTRY_URI}/o2-superoverlay:${TAG}
    ports:
      - "5009:8080"
    restart: always
  o2-tlv:
    container_name: tlv
    environment:
      BE_LOOKUP_URL: ${DOCKER_HOST_URL}/o2-wfs
      DOCKER_HOST_IP: ${DOCKER_HOST_URL}
      GEOCODER_URL: ${DOCKER_HOST_URL}/twofishes
      WFSURL: ${DOCKER_HOST_URL}/o2-wfs
      WMSURL: ${DOCKER_HOST_URL}/o2-wms
    image: ${DOCKER_REGISTRY_URI}/tlv:${TAG}
    ports:
      - "5015:8080"
    restart: always
  o2-wcs:
    container_name: o2-wcs
    depends_on:
      - o2-db
      - o2-stager
      - o2-web-proxy
    environment:
      DBHOST: o2-db
      DBNAME: omar_prod
      DBPASS: abc123
      DBPORT: 5432
      DBUSER: postgres_user
      DOCKER_HOST_IP: ${DOCKER_HOST_URL}
      OSSIM_DATA: /data
      SPRING_CLOUD_CONFIG_ENABLED: "false"
      SPRING_CLOUD_DISCOVERY_ENABLED: "false"
    image: ${DOCKER_REGISTRY_URI}/o2-wcs:${TAG}
    ports:
      - "5013:8080"
    volumes:
      - /data:/data
  o2-web-proxy:
    container_name: o2-web-proxy
    environment:
      DOCKER_HOST_IP: ${DOCKER_HOST_URL}
    image: ${DOCKER_REGISTRY_URI}/o2-web-proxy:${TAG}
    ports:
      - "80:80"
    restart: always
    volumes:
      - /data:/data
  o2-wfs:
    container_name: o2-wfs
    environment:
      DBHOST: o2-db
      DBNAME: omar_prod
      DBPASS: abc123
      DBPORT: 5432
      DBUSER: postgres_user
      DOCKER_HOST_IP: ${DOCKER_HOST_URL}
      O2URL: ${DOCKER_HOST_URL}/o2-omar
      OSSIM_DATA: /data
      SPRING_CLOUD_CONFIG_ENABLED: "false"
      SPRING_CLOUD_DISCOVERY_ENABLED: "false"
      TLV_URL: ${DOCKER_HOST_URL}/tlv
      WFSURL: ${DOCKER_HOST_URL}/o2-wfs
      WMSURL: ${DOCKER_HOST_URL}/o2-wms
    image: ${DOCKER_REGISTRY_URI}/o2-wfs:${TAG}
    ports:
      - "4998:8080"
    restart: always
  o2-wms:
    container_name: o2-wms
    environment:
      DBHOST: o2-db
      DBNAME: omar_prod
      DBPASS: abc123
      DBPORT: 5432
      DBUSER: postgres_user
      OSSIM_DATA: /data
      DOCKER_HOST_IP: ${DOCKER_HOST_URL}
      SPRING_CLOUD_CONFIG_ENABLED: "false"
      SPRING_CLOUD_DISCOVERY_ENABLED: "false"
    image: ${DOCKER_REGISTRY_URI}/o2-wms:${TAG}
    ports:
      - "4997:8080"
    restart: always
    volumes:
      - /data:/data
  o2-wmts:
    container_name: o2-wmts
    environment:
      DBHOST: o2-db
      DBNAME: omar_prod
      DBPASS: abc123
      DBPORT: 5432
      DBUSER: postgres_user
      DOCKER_HOST_IP: ${DOCKER_HOST_URL}
      OSSIM_DATA: /data
      SPRING_CLOUD_CONFIG_ENABLED: "false"
      SPRING_CLOUD_DISCOVERY_ENABLED: "false"
      WFSPORT:
      WFSSERVER: ${DOCKER_HOST_URL}/o2-wfs
      WMSPORT:
      WMSSERVER: ${DOCKER_HOST_URL}/o2-wms
    image: ${DOCKER_REGISTRY_URI}/o2-wmts:${TAG}
    ports:
      - "4999:8080"
    restart: always
