version: '2'
services:
  o2-web-proxy:
    build: ./o2-web-proxy
    image: ossimlabs/o2-web-proxy
    environment:
      DOCKER_HOST_IP: spring-cloud.radiantbluecloud.com
    ports:
      - "80:80"
    volumes:
    #  - /Users/Shared/data:/data
      - /home:/home
      - /Users:/Users
    restart: always
