version: '2'
services:
  o2-base:
#    build: ./o2-base
    container_name: o2-base
    image: ${DOCKER_REGISTRY_URI}/o2-base
  o2-db:
#    build: ./o2-db
    container_name: o2-db
    environment:
      POSTGRES_DB: omar_prod
      POSTGRES_PASSWORD: abc123
      POSTGRES_USER: postgres_user
    image: ${DOCKER_REGISTRY_URI}/o2-db
    ports:
      - "4990:5432"
    restart: always
