version: '2'
services:
  o2-web-proxy:
    build: ./o2-web-proxy
    environment:
      DOCKER_HOST_IP: localhost
    image: ossimlabs/o2-web-proxy
    ports:
      - "80:80"
    restart: always
    volumes:
      - /home:/home
      - /Users:/Users
